---
jupyter:
  jupytext:
    notebook_metadata_filter: all,-language_info
    split_at_heading: true
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.1'
      jupytext_version: 1.2.4
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  textbook:
    run: false
---

# Exercises on conditional statements

For background, please read the [conditional
statements](https://matthew-brett.github.io/cfd2019/07/conditional_statements)
introduction.

```{python}
# Load the OKpy test library and tests.
from client.api.notebook import Notebook
ok = Notebook('conditionals.ok')
```

This *if statement* is not properly defined, and will give a `SyntaxError`.  Fix it, so that `y` gets set to "That's right".

```{python}
x = 10
x > 4:
    y = "That's right"
# Show the value of y
y
```

```{python}
_ = ok.grade('q_1_y')
```


This `if` statement also gives a `SyntaxError`. Fix and run. It
should set `p` to have the value -8.

```{python}
p = -2
if p < 0
p
```

```{python}
_ = ok.grade('q_2_p')
```


Another `SyntaxError`; fix and run.  It should show `a divided
by 6 is 4`

```{python}
a = 24
if a / 6 == 4:
result = 'a divided by 6 is 4'
result
```

```{python}
_ = ok.grade('q_3_result')
```

We want an algorithm to choose a newspaper for someone to read
in the dentist's waiting room, given what we know about their
views on Brexit.

Write a function `choose_paper` that accepts a parameter
`posh_voter`, and returns `Times` if `posh_voter` has the value
`Soft Brexit`, otherwise returns `Telegraph` if `posh_voter`
has the value `Hard Brexit` otherwise returns `Daily Express`
if voter is `No-deal Brexit` otherwise returns `Guardian` if
voter has value `Remain`, otherwise returns None.

```{python}
def choose_paper(posh_voter):
    if posh_voter ...

# Some examples
print(choose_paper('Hard Brexit'))
print(choose_paper('Remain'))
print(choose_paper('Floating Brexit'))
```

```{python}
_ = ok.grade('q_4_brexit')
```

## Done

You're finished with the assignment!  Be sure to...

- **run all the tests** (the next cell has a shortcut for that),
- **Save and Checkpoint** from the "File" menu.

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in sorted(os.listdir("tests")) if q.startswith('q')]
```