---
jupyter:
  jupytext:
    metadata_filter:
      notebook:
        additional: all
        excluded:
        - language_info
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.6
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  textbook:
    run: false
---

# Exercises on functions

For background, please read the [functions]({{ site.baseurl
}}chapters/07/functions) introduction.

```{python}
# Run this cell
# Import the array library
import numpy as np

# Load the OKpy test library and tests.
from client.api.notebook import Notebook
ok = Notebook('first_functions.ok')
```

This function is not properly defined, and as it is now, will give
a `SyntaxError`.  Fix it, then run the call below to confirm it is working.

```{python tags=c("raises-exception")}
#<- function subtract(p, q):
def subtract(p, q):
#<-
    r = p - q
    return r
#<-
```

```{python}
subtract(5, 10)
```

```{python}
_ = ok.grade('q_1_subtract')
```


This function also gives a `SyntaxError`. Fix and run.

```{python tags=c("raises-exception")}
#<- def add(first_value, second_value)
def add(first_value, second_value):
#<-
    return first_value + second_value
#<-
```

```{python}
add(2, 3)
```

```{python}
_ = ok.grade('q_2_add')
```

Here is another error.  Fix and run.

```{python tags=c("raises-exception")}
#<-
def cube(a_variable):
#<-
#<- return a_variable ** 3
    return a_variable ** 3
```

```{python}
cube(3)
```

```{python}
_ = ok.grade('q_3_cube')
```


Consider this correct function definition:

```{python}
def add_then_multiply(a, b):
    added = a + b
    return added * b
```

Why does the cell below give you an error?

Leave the code in the cell as it is, but add a line at the beginning of the cell, so that `my_total` is equal to 60.

```{python tags=c("raises-exception")}
#- Your line here
#<- ...
added = 4
#<-
# Leave the two lines below unchanged.
result = add_then_multiply(10, 4)
my_total = result + added
my_total
#<-
```

```{python}
_ = ok.grade('q_3_1_my_total')
```


Write a function called `increase` that:

* accepts two arguments
* the body multiplies the first argument by 2 and the second by 3, adds the two
  resulting numbers, and returns the result.

If your function is right, the cell below should return 13.

```{python}
#- Your function here
def increase(a, b):
    return a * 2 + b * 3
```

```{python}
increase(2, 3)
```

```{python}
_ = ok.grade('q_4_increase')
```


This function will run, but it probably doesn't give you the result you expect.
Fix to give the result you expect and run.

```{python}
#<-
def divide(p, q):
    # Give result of dividing p by q
    result = p / q
#<-
    return result
```

```{python}
divide(10, 2)
```

```{python}
_ = ok.grade('q_5_divide')
```

## Back to simulations

Remember the three girls simulations?  We initially assumed that the chance of any one child being a girl was 0.5.

In fact, the [proportion of boys born in the
UK](https://www.gov.uk/government/statistics/gender-ratios-at-birth-in-great-britain-2010-to-2014)
is 0.513. Hence the proportion of girls is 1-0.513 = 0.487.

Here is a snippet of code that makes four random numbers and counts how many of these are less than 0.487.

```{python}
# Make four random numbers
randoms = np.random.uniform(0, 1, 4)
# Compare to 0.487
less_than = randoms < 0.487
n_less_than = np.count_nonzero(less_than)
n_less_than
```

Let's say we want to put that into a function, called `count_4_girls`.   The
function accepts no arguments, and returns the number of girls from a simulated
family of four, as above:

```{python}
#<--
def count_4_girls():
#<-     ...
    # Make four random numbers
    randoms = np.random.uniform(0, 1, 4)
    # Compare to 0.487
    less_than = randoms < 0.487
    return np.count_nonzero(less_than)

#<-
# Check what the function returns
count_4_girls()
#<-
```

```{python}
_ = ok.grade('q_5_1_count_4_girls')
```

Now we want a more general function that accepts two arguments `n` - the number
of children, and `p` the probability that any one child is a girl.   As before,
it returns the number of girls from a simulated family of `n` children, each
with `p` chance of being a girl.  Call the function `count_girls`.

```{python}
#<--
def count_girls(n, p):
#<-     ...
    # Make n random numbers
    randoms = np.random.uniform(0, 1, n)
    # Compare to p
    less_than = randoms < p
    return np.count_nonzero(less_than)

#<-
# Check what the function returns for n=5, p=0.25
print(count_girls(5, 0.25))
# Check what the function returns for n=3, p=0.6
print(count_girls(3, 0.6))
#<-
```

```{python}
_ = ok.grade('q_5_2_count_girls')
```
## Function world

Remember that, in function world, the function can see the variables at the top
level, but it cannot change what value the top-level variables point to.

Read the code the below, but do not run it.

Predict what you will see.  Will it be an error?  If not, what value will you
see?

Run it to see if you're right.

```{python}
a = 12

def my_function(b):
    return a * b

my_function(4)
```

This is now going into deeper water.

We know that, in function world, the function can see the variables at the top
level, but it cannot change what value the top-level variables point to.

Read the code the below, but do not run it.

Predict what you will see.  Will it be an error?  If not, what value will you
see?

Run it to see if you're right.  See if you can explain why you are right.  Call
your instructor over to check your explanation.

```{python}
a = 12

def function_two(b):
    a = b
    return a * b

function_two(4)
```

Edit this code cell with your explanation.

## Done

You're finished with the assignment!  Be sure to...

- **run all the tests** (the next cell has a shortcut for that),
- **Save and Checkpoint** from the "File" menu.

```{python}
# For your convenience, you can run this cell to run all the tests at once!
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]
```
